name: calcu
description: Just a calcu
version: 1.0.0
repository: https://github.com/withcenterdev5/calcu

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  function_tree: ^0.9.1
  
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
